const SAVE_WIDGET = 'SAVE_WIDGET';
const ADD_WIDGET = 'ADD_WIDGET';
const REMOVE_WIDGET = 'REMOVE_WIDGET';
const SELECT_WIDGET = 'SELECT_WIDGET';

export { SAVE_WIDGET, ADD_WIDGET, REMOVE_WIDGET, SELECT_WIDGET };
